feat: реализовал работу с учётом ТЗ 9-го спринта
Chernosmaga/java-filmorate pull request #4
Opened 2023-06-29 15:12 UTC by Chernosmaga

2023-06-29 16:28 UTC, PolnySkvorets commented
Не проходят условия по сборке - посмотри сообщение в логе ошибки сборки, там есть указание, что ты лишние файлы отправил в комите

2023-06-29 16:30 UTC, PolnySkvorets requested changes
Посмотри ТЗ - пункт Валидация. Он пропущен

2023-06-29 16:30 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LocalDate releaseDate;
Нет валидация этого поля. Посмотри пункт Валидация в ТЗ, там и по юзеру нужно сделать и по фильмам

2023-06-29 17:28 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LocalDate releaseDate;
По User валидация идёт в методе добавления и обновления пользователя. Имя может быть пустое по условию ТЗ. По Film валидация так же идёт в методах. Лучше всю валидацию в классах моделей делать? Или и там и тут повторять?

2023-07-04 08:44 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (!user.getEmail().contains("@") || user.getBirthday().isAfter(LocalDate.now())
Такую валидацию лучше выносить в отдельный метод или в класс. так проще будет воспринимать код

2023-07-04 08:46 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isEmpty() || user.getEmail().isBlank() || user.getLogin().isEmpty()
Аналогично замечанию выше, тем более что-то из проверок дублируется, также обратил внимание, что валидации у электронной почты разные. Должны ли они быть одинаковыми? Скорее всего да, если данные могут быть заменены

2023-07-04 08:47 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDuration() <= 0 || film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))
Дублируется вариация, лучше вынести в отдельный метод

2023-07-04 08:49 UTC, PolnySkvorets reviewed
Обрати внимание на валидацию, она дублируется, где-то не согласована. Лучше вынести её отдельно

2023-07-05 14:07 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.info("Incorrect user identifier was set as '{}'", user.getId());
Почему здесь неправильный id юзера?

2023-07-05 14:07 UTC, PolnySkvorets approved these changes

2023-07-06 08:51 UTC, merged