Add database
Chernosmaga/java-filmorate pull request #8
Opened 2023-08-18 10:03 UTC by Chernosmaga

Доработал проект с учётом ТЗ 11-го спринта:
1. Добавил сущности: Like, Genre, Friendship и Mpa
2. Для каждой сущности создал интерфейс и его имплементацию Dao
3. Реализовал сервисы для сущностей
4. Добавил файлы data.sql, schema.sql, data-base-diagram
5. Добавил информацию в README.md
6. Написал интеграционные тесты для каждого контроллера

2023-08-19 08:08 UTC, PolnySkvorets requested changes
Привет! В целом всё хорошо, но по требованиям написано так:
Таблицы созданы. Теперь можно заняться кодом, который будет отвечать за получение данных из базы.
Вам пригодятся созданные ранее интерфейсы UserStorage и FilmStorage. Напишите для них новую имплементацию — например, UserDbStorage и FilmDbStorage. Эти классы будут DAO — объектами доступа к данным.
Напишите в DAO соответствующие мапперы и методы, позволяющие сохранять пользователей и фильмы в базу данных и получать их из неё.


и ещё нужно в этом случае использовать аннотацию Qualifier. То есть старый код тоже должен был остаться

2023-08-20 10:25 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/service/local/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
По требованиям твои хранилища должны быть реализованы от одного общего интерфейса, инжектор должен быть по типу (интерфейсу), и поэтому и предлагается использовать аннотацию qualifier

2023-08-20 10:25 UTC, PolnySkvorets reviewed
Привет! По аннотации qualifier - посмотри комментарий.

2023-08-20 11:06 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/service/local/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Да, точно! Поторопился, забыл заимплементить, но возникает вопрос: могу ведь я объект класса InMemoryFilmStorage инжектить? Мне ведь не обязательно интерфейс использовать?

2023-08-21 15:17 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/film/FilmDbStorage.java
> +@Component("FilmDbStorage")
вот здесь, кстати, не обязательно указывать имя компонента, так как Спринг генерирует по имени класса по умолчанию, это нужно, если ты хочешь что-то не стандартное

2023-08-21 15:17 UTC, PolnySkvorets approved these changes
Окей, сейчас всё поправлено. отлично

2023-09-18 09:04 UTC, merged